services:

  api:
    build: . # Usamos el Dockerfile ya hecho
    ports:
      - "3000:3000" # PC:Contenedor
    volumes:
      - .:/app # Carpeta actual -> carpeta a la que vamos a mandar el cotenido dentro del contenedor
      - /app/node_modules # aisla el node_modules del contenedor
    environment:
      NODE_ENV: development

      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/neoglito
      ENCRYPTION_SECRET_KEY: ${ENCRYPTION_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      BACKEND_URL: ${BACKEND_URL:-http://localhost:3000}
      GITHUB_CALLBACK_URL: ${GITHUB_CALLBACK_URL:-http://localhost:3000/auth/github/callback}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED:-1}
      # URL para conectarnos a PostgreSQL
      # postgres:postgres → usuario:contraseña
      # @postgres → nombre del servicio de PostgreSQL
      # 5432 → puerto de PostgreSQL
      # repository_analyzer → nombre de la base de datos
      

    depends_on:
      postgres: # Si este no esta levantado nosotros no levantamos el api
        condition: service_healthy # Espera que se acepten conexiones reales
    command: >
      sh -c "npx prisma generate &&
             npx prisma db push &&
             npm run start:dev"

  postgres:
    image: postgres:17-alpine

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neoglito"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

    environment:
      POSTGRES_DB: neoglito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432" # PC:Contenedor

    volumes:
      - postgres_data:/var/lib/postgresql/data # Guarda los datos de postgresql fuera del cotenedor

  frontend:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    command: 
      sh -c "npm install &&
             npm --workspace @neoglito/web run dev -- --host 0.0.0.0"

volumes:
  postgres_data: 
